language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t seethentype/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true seethentype/docker-react npm run test


